//  "use client"
 import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // console.log(window)
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}> { children}</body>
    </html>
  );
}

function MyApp({ Component, pageProps }) {
  return (
    <RootLayout>
      <Component {...pageProps} />
    </RootLayout>
  );
}

// function SafeHydrate({ children }) {
//   return (
//     <div suppressHydrationWarning>
     
//     </div>
//   );
// }


